### ISSUE TITLE
Cisco 5520 Connection Exception

### ISSUE THREAD

**Issue by TeaObvious** [consulttelecom/cisco-wlc-pythonizer#1]
Everytime ssh_collect() attempts to execute `show running-config` it waits for like 20 Seconds and then throws an Exception as you ca see in Screenshot. SSH it self works, i can manually use it.
![screenshot-ee26b62c](https://user-images.githubusercontent.com/8144976/157697931-82cc2f0f-0c85-4194-9c0a-18be971b7960.jpg)

**Comment by consulttelecom** [comment]
Could you please add: 
- log file written during the issue (wlc-pythonizer.log from root folder)
- describe your environment (PC, OS version, Python version, libraries version)

**Comment by consulttelecom** [comment]
Close the issue as data to solve it was not provided.
