### ISSUE TITLE
Name_Error

### ISSUE THREAD

**Issue by Jorge-Carrillo-Ava** [consulttelecom/cisco-wlc-pythonizer#2]
Hi, 

I ran the container and I am able to get the config of the WLC using SSH, however when I try run some additional functionalities I am getting the error about the Name_Error.

Any suggestion about how to fix it ? 

![name_error](https://github.com/user-attachments/assets/da88e0eb-7a71-4ba3-8369-174993eb94d3)

**Comment by consulttelecom** [comment]
Hi,

The ssh_collect function returns dictionary with WLC config objects. 
Use the following commands to get the WLC config saved as variable:
**wlc_dict = ssh_collect()**
Then refer to the config your wlc as element of this dictionary by using its hostname:
**wlc = wlc_dict['MAS-Brandywine-WLC1']**

Let me know if that worked in your case
